language: cpp
compiler: gcc
sudo: required
install:
  - sudo apt-get --no-install-recommends -y install cxxtest
 before_install: sudo apt-get install -y cmake zlib1g-dev libfreetype6-dev libx11-dev libxrandr-dev libxcb1-dev libx11-xcb-dev libxcb-randr0-dev libxcb-image0-dev libflac-dev libogg-dev libvorbis-dev libvorbisenc2 libvorbisfile3 libopenal-dev libudev-dev libsndfile1-dev libglew-dev
    env: CMAKE_BUILD_TYPE=Release SFML_VER=2.5.1 TARGET_BITS=64 ZPG_PACKER_BIN=/usr/bin/zpg_packer
    stage: Release64
    addons:
      artifacts:
        paths:
        - $TRAVIS_BUILD_DIR/build-Release/MVRunner
        - $TRAVIS_BUILD_DIR/build-Release/*.tar.gz
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: windows
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
script: 
    - make
    - git ls-files src/ | xargs clang-format -i && git diff --exit-code