language: cpp
compiler: gcc
dist: xenial
sudo: required
before_script:
  - sudo ldconfig
  - git clone https://github.com/SFML/SFML /tmp/SFML
  - cd /tmp/SFML
  - git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
  - cmake .
  - cmake --build . -- -j4
  - sudo make install
  - cd -

script:
  - make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code