language: cpp
compiler: gcc
dist: xenial
sudo: required
jobs:
  include:
  - stage: Unit tests
    name: Linux (gcc 6)
    os: linux
    dist: xenial
    env: COMPILER=g++-6
    services:
    - xvfb
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - libudev-dev
        - libxrandr-dev
        - libgl1-mesa-dev
    cache:
      directories:
      - $HOME/SFML-2.5.0_LINUX

script:
  - make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code